/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("java")
    id("com.gradleup.shadow") version "8.3.0"
}

version = "1.0.1"
group = "org.cda"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    // Lombok
    compileOnly("org.projectlombok:lombok:1.18.32")
    annotationProcessor("org.projectlombok:lombok:1.18.32")
    testCompileOnly("org.projectlombok:lombok:1.18.32")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.32")

    // Slf4j
    implementation("org.slf4j:slf4j-api:2.1.0-alpha1")
    implementation("org.slf4j:slf4j-simple:2.1.0-alpha1")

    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)

    // This dependency is used to connecto to azure IoT Hub
    implementation("com.microsoft.azure.sdk.iot:iot-device-client:2.5.0")

    // This dependency is used to parse objects to JSON and JSON to objects
    implementation("com.google.code.gson:gson:2.11.0")

    // This dependency is used to retrieve OS data
    implementation("com.github.oshi:oshi-core:6.6.1")

    // This dependency is used to communicate with Raspberry Pi's GPIO
    implementation("com.pi4j:pi4j-plugin-linuxfs:2.6.1")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = "org.cda.Main"
    }
}

tasks.shadowJar {
    manifest {
        archiveClassifier.set("")
    }
    destinationDirectory.set(file("${project.buildDir}/jar"))
    archiveFileName.set("cda-${project.version}.jar")
    from(sourceSets.main.get().output)
}

application {
    // Define the main class for the application.
    mainClass = "org.cda.Main"
}
