/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    compileOnly("org.projectlombok:lombok:1.18.32")
    annotationProcessor("org.projectlombok:lombok:1.18.32")
    testCompileOnly("org.projectlombok:lombok:1.18.32")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.32")

    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)

    // This dependency is used to parse objects to JSON and JSON to objects
    implementation("com.google.code.gson:gson:2.11.0")

    // This dependency is used to retrieve OS data
    implementation("com.github.oshi:oshi-core:6.6.1")

    // This dependency is used to communicate with Raspberry Pi's GPIO
    implementation("com.pi4j:pi4j-plugin-linuxfs:2.6.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.cda.Main"
}

tasks.withType<Copy> {
    from("src/main/resources") {
        include("config.props")
        include("config.props.template")
        into("build/resources/main")
    }
}
